### PR TITLE
docs: add auto formatting of style note

### PR DESCRIPTION
**Pull request by webfansplz**
I thought it was necessary to add this comment to let the user know how automatic formatting of `style` works.

If you don't think it's necessary, just close the PR. Thanks~

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
I don't mind adding it, as a context, can you describe the problem you encountered?

**Comment by webfansplz** [comment]
> I don't mind adding it, as a context, can you describe the problem you encountered?

I was setting this option in my user section `.vscode/settings.json`,this led to the automatic formatting of `style` to not work . 😂
```json
"[vue]": {
 "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**Comment by Shinigami92** [comment]
Little bit sad that this needs to be mentioned in an unrelated repo, but yes I have configured this also. But not because of Volar, but because it is just the needed configuration to format code in VSCode with the wanted formatter 🤷 

I have:

```jsonc
{
 "[html]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[java]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.formatOnType": false
  },
  "[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[json]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[jsonc]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[markdown]": {
    "files.trimTrailingWhitespace": false,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[vue]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
  "[jade]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  // ...
}
```

**Comment by johnsoncodehk** [comment]
@Shinigami92 I hope to clean up the document in the future. Now there is indeed some irrelevant information.

**Pull request merged**
