### PR TITLE
feat: 🎸 finish 235

### LINKED ISSUE #235: [FR] Setting to add file extension for `.js`/`.jsx` files in import path intellisense
Currently, no file extension is shown in the path intellisense for `.js`/`.jsx` files like `.vue` files do, would be great if we have the option to enable that.

Please note: the desired behavior should be completing what's shown in the intellisense, e.g. `Foo.ts`/`Foo.tsx` being shown as `Foo`, and completed as `Foo`, `Foo.js`/`Foo.jsx` being shown as they are, and completed as they are.

image

image

Repro: https://github.com/wenfangdu/volar-jsx-import-vue-repro

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
resolved #235

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
https://user-images.githubusercontent.com/17974631/120356657-279ab500-c337-11eb-8803-39bfd55e2d40.mp4

**Comment by wenfangdu** [comment]
Thanks for the PR! However, for `.ts` and `.tsx` files, I think this setting should bypass them since when doing so, the following will happen:

image

image

**Comment by IWANABETHATGUY** [comment]
https://user-images.githubusercontent.com/17974631/120433897-5acc5b00-c3ae-11eb-9d98-5b3ef61f85f0.mp4

this pr doesn't complete the extension, just add the extension to the label.
cc @johnsoncodehk

**Comment by wenfangdu** [comment]
Oh, sorry, didn't notice that. The desired behavior should be completing what's shown in the intellisense, e.g. `Foo.tsx` being shown as `Foo`, and completed as `Foo`, `Foo.js`/`Foo.jsx` being shown as they are, and completed as they are.

**Comment by johnsoncodehk** [comment]
Thanks for the PR!

But TS already has `typescript.preferences.importModuleSpecifierEnding` setting and I expect to reuse it. I will check how [typescript-language-features](https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features) handle all the TS settings and try to make same achieve in volar. (Maybe do it in the next weekend)

**Pull request closed without merging**
