### PR TITLE
feat: 🎸 add warning notification if current workspace is not a volar project  

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
image

**Comment by IWANABETHATGUY** [comment]
image

**Comment by IWANABETHATGUY** [comment]
It's better add some lint , format config to unifiy contributor‘s  code style

**Comment by johnsoncodehk** [comment]
Thanks for your contribution, this is a nice ux improve!

Also need to handle monorepo, I will check how to change.

**Comment by johnsoncodehk** [comment]
I tried to add rename, but it was difficult to read. I'm searching a more readable way to write test code.

**Pull request merged**
