### PR TITLE
Feat: support single line comment

### PR DESCRIPTION
**Pull request by appleshowc**
it will make `Better Comments` extension work.
image

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
Thanks but vue is extend language of html, and `//` is not valid html comment, please reference changes to https://github.com/aaron-bond/better-comments/pull/392.

**Comment by Vincebe** [comment]
> it will make `Better Comments` extension work. image

Thanks !

**Comment by hrenx** [comment]
> 
Mean type those code can make `Better Comments`  Work? But it's seem not work at my vue file.
image

**Comment by edwinhuish** [comment]
> > 
> 
> Mean type those code can make `Better Comments` Work? But it's seem not work at my vue file. image

open your vscode plugin path, for windows in ```C:\Users\[USER]\.vscode\extensions```,  find out the volar plugin and modify the ``` languages/vue-language-configuration.json ``` .

It works well for me.

**Comment by hrenx** [comment]
> > > 
> > 
> > 
> > Mean type those code can make `Better Comments` Work? But it's seem not work at my vue file. image
> 
> open your vscode plugin path, for windows in `C:\Users\[USER]\.vscode\extensions`, find out the volar plugin and modify the `languages/vue-language-configuration.json` .
> 
> It works well for me.
> 
> PS: remember to restart the vscode.

thank you! I final understand how to config. 
image

**Comment by JuZiTuanTuan** [comment]
thank you，it works🫡

**Pull request closed without merging**
