### PR TITLE
Rewrite `vscode-vue-languageservice`

### LINKED ISSUE #763: Rewrite `vscode-vue-languageservice`
The core code is written in the process of exploration, it is unmaintainable by others currently, planned to be rewritten in February 2022.

### PR DESCRIPTION
**Pull request by johnsoncodehk**
Close #763

### CODE REVIEW

**Comment by yaegassy** [comment]
@johnsoncodehk Let me ask you a question. Does `volar.autoCompleteRefs` work with this `rewrite-language-features` branch?

**Comment by johnsoncodehk** [comment]
`GetAutoQuoteEditsRequest`, `GetTagCloseEditsRequest`, `GetWrapParenthesesEditsRequest`(#859), `GetRefCompleteEditsRequest` all is combine to single `AutoInsertRequest`.

`volar.autoCompleteRefs` setting now read in language server, so you don't need to check `volar.autoCompleteRefs` and other auto insert features settings in language client.

**Comment by yaegassy** [comment]
> yes it's works, `GetAutoQuoteEditsRequest`, `GetTagCloseEditsRequest`, > `GetWrapParenthesesEditsRequest`(#859), `GetRefCompleteEditsRequest` all is combine to single `AutoInsertRequest`.
>
> `volar.autoCompleteRefs` setting now read in language server, so you don't need to check `volar.autoCompleteRefs` and other auto insert features settings in language client.

Thanks for the explanation. I was trying to rewrite to `autoInsertion.ts` in `coc-volar`.

- <https://gist.github.com/yaegassy/e8cb41c9518ca6a82c6f25f5658cef68>

I asked this question because I was curious because `autoClosingTags` and `autoCreateQuotes` worked but `autoCompleteRefs` did not.

Thank you once again for your response. 🙇

**Comment by johnsoncodehk** [comment]
@yaegassy no problem, let me know anytime if any problems you found.

Thank you to quick adjustment the language client!

**Comment by yaegassy** [comment]
@johnsoncodehk There seems to be a typo. `difinition` -> `definition`. <https://github.com/johnsoncodehk/volar/pull/1009/commits/2cac63e98f5b4556477902088f457725b0827c56>

**Comment by johnsoncodehk** [comment]
NOTE: The refactoring is not done, this is just a paragraph

**Pull request merged**
