### PR TITLE
feat: support inlay hints

### PR DESCRIPTION
**Pull request by johnsoncodehk**
LSP Issue: https://github.com/microsoft/language-server-protocol/issues/956
Document: https://code.visualstudio.com/updates/v1_60#_inlay-hints-for-javascript-and-typescript

This feature still in VSCode Proposed API, LSP don't support yet, currently implement by VSCode client API, and only able to test in VSCode Insider.

Setup:

1. Launch VSCode Insider (1.60 later) by command `code-insiders . --enable-proposed-api johnsoncodehk.volar`.
2. Install [volar-0.27.13-inlay-hints.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/7108477/volar-0.27.13-inlay-hints.2.vsix.zip) to VSCode Insider. (You can bulit it youself by `npm run pack` command)
3. Search `inlayHints` in VSCode settings and enable features your needs.

Reference: https://code.visualstudio.com/api/advanced-topics/using-proposed-api#sharing-extensions-using-the-proposed-api

### CODE REVIEW

**Comment by Kingwl** [comment]
Looks good.

**Comment by johnsoncodehk** [comment]
@oxk4r01 This PR is implement in 0.27.13, how do you update to 0.28?

**Comment by oxk4r01** [comment]
VSCode downloaded automatically v0.28. I had to disable auto updating for the extension.

**Comment by johnsoncodehk** [comment]
@oxk4r01 This feature is not available in the automatically updated version, because vscode does not allow release experimental features, please wait for this feature to leave experimental on vscode.

**Comment by oxk4r01** [comment]
Then maybe it changed the version due to the sync settings config. I have v0.28 in another computer. I don't know.

**Comment by Shinigami92** [comment]
Would you like to give this a new try? :smiley:

**Comment by johnsoncodehk** [comment]
> Would you like to give this a new try? 😃

Can't implement yet, still have to wait to out of proposed in vscode.

**Pull request closed without merging**
