### PR TITLE
fix(docs): extend vue 2 info regarding types

### PR DESCRIPTION
**Pull request by rchl**
I know this puts the instructions upside-down since you've been suggesting to remove `Vue.extend` while I've changed it to recommend `Vue.extend`. The rationale is that, based on testing and as stated in the comments in #741, `Vue.extend` is really the way to go to fix the inevitable type issues in Vue 2 projects and I haven't really found any downsides to it.

If you have any specific examples where `Vue.extend` would makes things worse type-wise then I can tweak the wording or change it completely.

Note that when working with Vetur, I'm used to having to help the type system in many situations by adding manual JSDoc comments (when using JS) so I would expect this to be the case with Volar also. But that shouldn't change the fact that `Vue.extend` is required in the first place.

Related #741

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
If you don't care about the component props / events type-check and auto-complete in template, `Vue.extend` is fine.

Otherwise you need to migrate to defineComponent from `@vue/composition-api` to support these features.

**Comment by rchl** [comment]
> If you don't care about the component props / events type-check and auto-complete in template,

I'm trying to say that this already **works**. Check the simple https://github.com/rchl/volar-vue2-test project for example.

I know that using Composition API works better in terms of type support but I just can't understand why do you keep saying that `Vue.extend` breaks auto-complete in the template. This is simply not true. I'd need you to explain this clearly before I adjust the text.

**Comment by johnsoncodehk** [comment]
Sorry for not making it clear, I am talking about cross-component props auto-complete and type-checking.

It should have auto-complete for `:test`.
螢幕截圖 2021-12-04 上午2 15 18

It should have type error for `:test`.
螢幕截圖 2021-12-04 上午2 16 05

**Comment by rchl** [comment]
But that's not relevant to whether someone is using `Vue.extend` or not.

And even so, it works in the my test project above any way. Try adding a `test` property to `Tutorial` component in `pages/index.vue`.

**Comment by johnsoncodehk** [comment]
Without `Vue.extend` it should works. But actually I planned to abandon support for cross-component props type-checking with `export default { ... }`, so I hope remove mentioned `export default { ... }` in this pr.

image

So user only have 3 option in future:
- `export default Vue.extend({ ... })`: support type-check in `<script>` and `<template>`, but not support cross-component type-check.
- `export default defineComponent({ ... })`: support type-check in `<script>` and `<template>` and with cross-component
- class component: support type-check in `<script>` and `<template>` and with cross-component with additional code. (#21)

**Comment by rchl** [comment]
Seems to be working with `Vue.extend` also.

Screenshot 2021-12-03 at 20 27 21

So to conclude:
 - cross-component props type-checking seems to be working with both `Vue.extend` and without
 - Type-checking within the component requires `Vue.extend` to work properly.

With that said, is there anything you want to change me in this PR?

**Comment by johnsoncodehk** [comment]
@rchl emmmm it's vetur report. :S

**Comment by rchl** [comment]
🤦  Sorry. That's my default setup and forgot to switch for testing.

But now that I've switched to Volar, it doesn't seem to work with either `export default {}` or export default Vue.extend({})`.

Screenshot 2021-12-03 at 20 33 34

**Comment by johnsoncodehk** [comment]
Maybe `Tutorial.vue` is still `Vue.extend({ ... }) `.

**Comment by rchl** [comment]
No, you can try yourself on the project. Pushed Vue.extend removal

**Comment by johnsoncodehk** [comment]
Sorry, also need `lang="ts"`.

**Comment by rchl** [comment]
OK, can reproduce that case.

That complicates things since now we have more variables to potentially document.

As far as using plan JS, `Vue.extend` still seems like a preferred option.

As far as TS, are you saying that it will work only with `Vue.extend` (based on [your comment](https://github.com/johnsoncodehk/volar/pull/750#issuecomment-985755033)? In which case, doesn't my point still stands that using `Vue.extend` is recommended?

**Comment by johnsoncodehk** [comment]
I think we don’t need to advise users what to use, just state the facts, which methods are supported and which are not.

|                                              | Component options type-checking in `<script>`                | Interpolation type-checking in `<template>` | Cross-component props type-checking     |
|----------------------------------------------|--------------------------------------------------------------|---------------------------------------------|-----------------------------------------|
| `export default { ... }` with JS             | Not Support                                                  | Not support                                 | Not support                             |
| `export default { ... }` with TS             | Not Support                                                  | Support but planed to abandon in future     | Support but planed to abandon in future |
| `export default Vue.extend({ ... })` with JS | Not Support                                                  | Not support                                 | Not support                             |
| `export default Vue.extend({ ... })` with TS | Limited (Support `data` types but not support `props` types) | Not support                                 | Not support                             |
| `export default defineComponent({ ... })`    | Support                                                      | Support                                     | Support                                 |
| Class component                              | Support                                                      | Support with additional code (#21)          | Support with additional code            |

**Comment by rchl** [comment]
Is this a typo?

Screenshot 2021-12-05 at 20 35 08

`Vue.extend` is exactly what is supposed to make those work.

**Comment by johnsoncodehk** [comment]
`Vue.extend` only working with js but not working with ts on my tests.

You can try:

```js
// test-js.js
import Vue from 'vue'

Vue.extend({
	data: () => ({
		foo: 123
	}),
	mounted() {
		this.foo // any
	},
})
```

```ts
// test-ts.ts
import Vue from 'vue'

Vue.extend({
	data: () => ({
		foo: 123
	}),
	mounted() {
		this.foo // number
	},
})
```

**Comment by rchl** [comment]
I would swear that JS was working before but it doesn't seem like it. Maybe I was confused due to my Vetur running again...

In that case I would say that Options API Vue2 support is not in a state that is usable in a real world projects so maybe it shouldn't be supported/advertised at all?

Having to add `Vue.extend` everywhere is one major obstacle. I don't think that it's feasible to do that everywhere in an existing, potentially large projects.

The other issue is that type checking is spotty at best so many of the issues wouldn't be caught. Vetur is not ideal either, mind you, but certainly more complete.

**Comment by johnsoncodehk** [comment]
> I would swear that JS was working before but it doesn't seem like it. Maybe I was confused due to my Vetur running again...

I think this has not relate to vetur/volar because it is reproduced in vanilla js/ts.

> In that case I would say that Options API Vue2 support is not in a state that is usable in a real world projects so maybe it shouldn't be supported/advertised at all?

With defineComponent from `@vue/composition-api` I think the support for vue2 is already quite good.

> Having to add `Vue.extend` everywhere is one major obstacle. I don't think that it's feasible to do that everywhere in an existing, potentially large projects.

Users only need to continue to use vetur. If they don't want to modify the code, they don't have to switch to volar.
btw the method I recommend is defineComponent instead of Vue.extend.

> The other issue is that type checking is spotty at best so many of the issues wouldn't be caught. Vetur is not ideal either, mind you, but certainly more complete.

Are you talking about using Vue.extend? If yes, it is because vetur has done some work outside of Vue.extend to support more types. But like I said, doing so destroys predictability, so Volar won't do it. The component type will be completely controlled by the vue library. If Vue.extend is missing the props type, the user should not get the props type in the template, otherwise it is a bug for volar.

**Comment by rchl** [comment]
> With defineComponent from `@vue/composition-api` I think the support for vue2 is already quite good.

But I'm talking about the Options API specifically. Can `definedComponent` be used with Options API? If so then I'm fine with just including that info the readme (the table you've posted).

**Comment by johnsoncodehk** [comment]
> Can `definedComponent` be used with Options API?

Yes, it is comprehensively better than Vue.extend.

**Comment by yangHeavy** [comment]
> I think we don’t need to advise users what to use, just state the facts, which methods are supported and which are not.
> 
> Component options type-checking in `<script>`	Interpolation type-checking in `<template>`	Cross-component props type-checking
> `export default { ... }` with JS	Not support	Not support	Not support
> `export default { ... }` with TS	Not support	Support but planed to abandon in future	Support but planed to abandon in future
> `export default Vue.extend({ ... })` with JS	Not support	Not support	Not support
> `export default Vue.extend({ ... })` with TS	Limited (Support `data` types but not support `props` types)	Limited	Not support
> `export default defineComponent({ ... })`	Support	Support	Support
> Class component	Support	Support with additional code (#21)	Support with additional code

hello, i have seen this property table for prop type check.
First, i am Very exciting volar supports the vue2.0 type check.
But what about `vue-property-decorator` use `@prop` ? Can it have the type check and auto-complete? It seems belong to class component type.
See the example in this repository: [https://github.com/MAG-Christian-Birkl/volar-vue2-test-mag](https://github.com/MAG-Christian-Birkl/volar-vue2-test-mag)
Although I have add `static components: { HelloWorld: typeof HelloWorld }`, it still failed with type check.

**Comment by johnsoncodehk** [comment]
@yangHeavy it's a example what you can define in class component for volar.

```ts
export default class Foo extends Vue {
  static components: {
    MyComp: typeof MyComp
  }
  $props!: {
    optionalProp?: string;
    requiredProp: string;
  }
  $emit!: {
    (e: 'my-event-1'): void
    (e: 'my-event-2', arg1: string, arg2: number): void
  }
  $scopedSlots!: { // $scopedSlots for vue2, $slots for vue3
    'my-slot-1': () => VNode[]
    'my-slot-2': (bindings: { arg1: string, arg2: number }) => VNode[]
  }
}
```

---

In App.vue of the repo, you need to define `static components: { HelloWorld: typeof HelloWorld }` in the class component.

**Comment by yangHeavy** [comment]
Thanks for answer for how to use class component with volar. But there some problems too.
1. I have to use declarations, otherwise I get an error

2. so `vue-property-decorator` use `@prop` can't  check?

**Comment by johnsoncodehk** [comment]
@yangHeavy yes you need to define it repeatedly. decorator == no TS support :)

**Comment by yangHeavy** [comment]
I see. But there are some problems when I have defined the variable. 
I define it string, use it with number, but volar doesn't get an error.
image

**Comment by johnsoncodehk** [comment]
@yangHeavy in this case you need to define `$props!: { what?: string }` additionally.

**Comment by yangHeavy** [comment]
@johnsoncodehk  Sorry, I found it. I try it success!! I will share Volar with my colleagues and weigh whether we need to use variable type checking in cases where we need to define it twice. Thank you very much.

**Comment by johnsoncodehk** [comment]
@yangHeavy as a workaround, you could shim the component type to auto define `$props`.

In this workaround, you need to write `readonly` additionally to distinguish this is a prop not component data.

```ts
@Component({})
class HelloWorld extends Vue {
  @Prop() readonly requiredProp!: string;
  @Prop() readonly optionalProp?: string;
  nonProp?: string;
}

export default HelloWorld as ShimComponentProps<typeof HelloWorld>;
```

helper types:
```ts
type ShimComponentProps<T extends new (...args: any) => any> = new () => InstanceType<T> & {
  $props: ComponentProps<InstanceType<T>>
};

type ComponentProps<T> =
  { [K in keyof Pick<T, ReadonlyKeys<T> & OptionalKeys<T>>]?: T[K] }
  & { [K in keyof Pick<T, ReadonlyKeys<T> & RequiredKeys<T>>]: T[K] };

type Equal<X, Y> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? true : false;

type ReadonlyKeys<
  T,
  U extends Readonly<T> = Readonly<T>,
  K extends keyof T = keyof T
  > = K extends keyof T ? Equal<Pick<T, K>, Pick<U, K>> extends true ? K : never : never;

type OptionalKeys<T> = keyof {
  [K in keyof T as T[K] extends Required<T>[K] ? never : K]: T[K]
};

type RequiredKeys<T> = keyof {
  [K in keyof T as T[K] extends Required<T>[K] ? K : never]: T[K]
};
```

**Comment by yangHeavy** [comment]
@johnsoncodehk `ShimComponentProps` is a nice typescript coding example! But it still has some problems after i test it.
image
`ShimComponentProps` doesn't extends Vue! And this will cause @Components() can't identify `HelloWorld`.
image

**Comment by rchl** [comment]
I've applied your suggestion with some minor changes. Let me know if it looks better now.

**Comment by johnsoncodehk** [comment]
LGTM, thank you!

**Comment by hexf00** [comment]
> @yangHeavy it's a example what you can define in class component for volar.
> 
> ```ts
> export default class Foo extends Vue {
>   static components: {
>     MyComp: typeof MyComp
>   }
>   $props!: {
>     optionalProp?: string;
>     requiredProp: string;
>   }
>   $emit!: {
>     (e: 'my-event-1'): void
>     (e: 'my-event-2', arg1: string, arg2: number): void
>   }
>   $scopedSlots!: { // $scopedSlots for vue2, $slots for vue3
>     'my-slot-1': () => VNode[]
>     'my-slot-2': (bindings: { arg1: string, arg2: number }) => VNode[]
>   }
> }
> ```
In vue2 project, the type of scope parameter is deduced as vnode [] | undefined, I want to know what happened in the middle, or does it not have this feature?

**Comment by hexf00** [comment]
> > @yangHeavy it's a example what you can define in class component for volar.
> > ```ts
> > export default class Foo extends Vue {
> >   static components: {
> >     MyComp: typeof MyComp
> >   }
> >   $props!: {
> >     optionalProp?: string;
> >     requiredProp: string;
> >   }
> >   $emit!: {
> >     (e: 'my-event-1'): void
> >     (e: 'my-event-2', arg1: string, arg2: number): void
> >   }
> >   $scopedSlots!: { // $scopedSlots for vue2, $slots for vue3
> >     'my-slot-1': () => VNode[]
> >     'my-slot-2': (bindings: { arg1: string, arg2: number }) => VNode[]
> >   }
> > }
> > ```
> 
> In vue2 project, the type of scope parameter is deduced as vnode [] | undefined, I want to know what happened in the middle, or does it not have this feature?

https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features

I followed the steps prompted in the document and found that the type overload of Vue needs to be deleted. The slot parameter type prompt of volar can take effect

**Comment by aziztitu** [comment]
@johnsoncodehk I was able to follow your instructions and get the type checking for Props and ScopedSlots working, but for the Emit, it seems like there might be a type mismatch.

image

In the Vue types package, it looks like $emit expects a Function type. So when using an object with a bunch of functions as it's type, it complains due to the conflict.

image


Should we override a different variable other than $emit instead?

**Comment by johnsoncodehk** [comment]
@aziztitu Vue 2 do not support typed emit, if you do want to, you can try omit `$emit` from `Vue` in interface.

**Comment by aziztitu** [comment]
@johnsoncodehk Gotcha. I was able to at least get the Event suggestions working by hacking it like this:

image
image


This stops any errors from being thrown, but the only issue is there's no actual type checking happening. It seems to think that all events now take 2 args :D 
image


But like you said, it probably is just due to the fact that it's Vue 2. I can just remove the args from the Emit type, and live with it for now :)

**Comment by johnsoncodehk** [comment]
@aziztitu please track #1855

**Pull request merged**
