### PR TITLE
chore: publish to open-vsx

### PR DESCRIPTION
**Pull request by lukashass**
This adds publishing to open-vsx in a GitHub action.

### Things you would still need to do:

1. Register at https://open-vsx.org/
2. Set `OVSX_PAT` GitHub action secret
3. [Claim](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) the `Vue` namespace

### Additional notes

I published https://open-vsx.org/extension/lukashass/volar for testing.

Publishing with target-platform support is blocked by:
- https://github.com/eclipse/openvsx/issues/450
- https://github.com/EclipseFdn/open-vsx.org/issues/1084.

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
Hi @lukashass, thanks for your PR, but I decided not add `ovsx publish` to local publish process, but I can accept setup a GitHub action in this repo to run `ovsx publish` when new tag is pushed, would you want to update this PR to GitHub action?

**Comment by lukashass** [comment]
Sure, will do.

**Comment by lukashass** [comment]
@johnsoncodehk The GitHub action should now be ready. All you need to do is described in the description :wink: 

A test run can be found at https://github.com/lukashass/volar/actions/runs/3324306875/jobs/5495742234

**Comment by mlbiche** [comment]
Just restarted VSCodium, I am seeing now an installed extension from Vue with the same name as @johnsoncodehk one's. The first one is version 1.0.9 and has been published 3 days ago, while the second one is blocked to version 0.30.1.

https://open-vsx.org/extension/Vue/volar

Is it related to this merge request ?

**Comment by lukashass** [comment]
@mlbiche The extension was renamed some time ago. See https://github.com/johnsoncodehk/volar/issues/1124

This PR will only replace the publishing process of `Vue.volar` which is currently in https://github.com/open-vsx/publish-extensions.

@johnsoncodehk Maybe we should check if Open VSX can move/redirect `johnsoncodehk.volar` to `Vue.volar`

**Comment by lukashass** [comment]
@johnsoncodehk Yes, we _can_ do that. Tough I would prefer if you create your own token (in the long run).

I could also claim the namespace myself - citing this discussion - to be able to create a bot account and/or transfer ownership to you later.

Where should I send you the access token?

**Comment by johnsoncodehk** [comment]
@lukashass You can find me on discord (My id is johnsoncodehk#0495), or email johnsoncodehk@gmail.com. Thanks.

**Comment by johnsoncodehk** [comment]
Hey @lukashass 👋, the last release CI just failed and prompted the folloing message. Is this something you can handle? Thanks in advance.
image

Doc link: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-log-in-and-sign-the-publisher-agreement

**Comment by lukashass** [comment]
@johnsoncodehk I'm not sure what the problem is, cause my profile says:

> You signed the Eclipse Foundation Open VSX Publisher Agreement 2 years ago.

I created an issue over here: https://github.com/eclipse/openvsx/issues/868

There are also some similar reports about expired agreements, so I presume it is a bug with the registry and we just try to run the job again now or in a few days.

**Comment by lukashass** [comment]
@KazariEX I requested to change the pre-release status of the existing releases here: https://github.com/EclipseFdn/open-vsx.org/issues/4022

For future releases I submitted https://github.com/vuejs/language-tools/pull/5377

**Comment by bytemain** [comment]
@lukashass Hello, it looks like the latest version on open-vsx is still pointing to 3.0.0-alpha.8, I think the alpha version should not be latest version?

CleanShot 2025-06-04 at 16 51 58@2x


CleanShot 2025-06-04 at 16 51 47@2x

**Pull request merged**
